spring.application.name=transactions
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/transactions}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgre}
spring.jpa.hibernate.ddl-auto=update